import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from '@playwright/test';
import { createServer } from 'vite';
import { createRuntime } from './local-runtime.mjs';

const runtime = await createRuntime({port:8787,persist:false});
const server = await createServer({server:{host:'127.0.0.1',port:5173,strictPort:true}});
let browser;
try {
  await server.listen();
  browser = await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{})});
  const context = await browser.newContext({viewport:{width:1280,height:900}});
  const page = await context.newPage(); page.setDefaultTimeout(15000); const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://127.0.0.1:5173/');
  await page.getByLabel('クライアントの呼称',{exact:true}).fill('A社');
  await page.getByRole('button',{name:'案件を作成',exact:true}).click();
  await page.getByLabel('業種',{exact:true}).selectOption('career');
  await page.getByLabel('目的',{exact:true}).selectOption('leads');
  await page.getByRole('button',{name:'設計を保存',exact:true}).click();
  await page.getByText('ターゲット像は既定値で補完しました。',{exact:true}).waitFor();
  let releaseSave;
  const delayed = new Promise(resolve => { releaseSave = resolve; });
  await page.route('**/api/projects/*/channel', async route => {
    const reply = await route.fetch(); await delayed; await route.fulfill({response:reply});
  });
  await page.getByRole('button',{name:'設計を保存',exact:true}).click();
  await page.getByRole('navigation',{name:'制作の流れ'}).getByRole('link',{name:'企画メモ・企画シート',exact:true}).click();
  await page.getByLabel('企画メモ',{exact:true}).fill('遅延応答中の新しい下書きです');
  releaseSave();
  await page.waitForFunction(()=>document.querySelector('main')?.getAttribute('aria-busy')!=='true');
  assert.equal(await page.getByLabel('企画メモ',{exact:true}).inputValue(),'遅延応答中の新しい下書きです');
  await page.unroute('**/api/projects/*/channel');
  const nav=page.getByRole('navigation',{name:'制作の流れ'});
  await nav.getByRole('link',{name:'企画メモ・企画シート',exact:true}).click();
  await page.getByLabel('企画メモ',{exact:true}).fill('転職でよくある質問に答える企画です');
  await page.getByRole('button',{name:'自動分類する',exact:true}).click();
  await page.getByRole('button',{name:'企画シートを作成',exact:true}).waitFor();
  await page.getByLabel('企画型',{exact:true}).selectOption('faq');
  await page.getByRole('button',{name:'企画シートを作成',exact:true}).click();
  await page.getByRole('heading',{name:'タイトル案',exact:true}).waitFor();
  await nav.getByRole('link',{name:'台本構成・撮影チェックリスト',exact:true}).click();
  await page.getByRole('button',{name:'台本構成を作成',exact:true}).click();
  await page.getByLabel('話すことの要点',{exact:true}).first().fill('最初に転職の悩みを紹介します');
  await page.getByLabel('撮影メモ',{exact:true}).first().fill('正面から撮影します');
  await page.getByRole('button',{name:'要点・撮影メモを保存',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('[role="status"]')?.textContent==='保存しました。');
  await nav.getByRole('link',{name:'スケジュール',exact:true}).click();
  await page.getByLabel('投稿日',{exact:true}).fill('2099-10-30');
  await page.getByRole('button',{name:'逆算スケジュールを作成',exact:true}).click();
  await page.getByLabel('企画確定 状態',{exact:true}).selectOption('done');
  await page.getByRole('button',{name:'更新',exact:true}).first().click();
  await page.waitForFunction(()=>document.querySelector('[role="status"]')?.textContent==='保存しました。');
  await nav.getByRole('link',{name:'編集指示書',exact:true}).click();
  await page.getByRole('button',{name:'編集指示書を作成',exact:true}).click();
  await page.getByText(/話すことの要点: 最初に転職の悩みを紹介します/).waitFor();
  await mkdir('WORK/screenshots',{recursive:true});
  await page.screenshot({path:'WORK/screenshots/brief-desktop.png',fullPage:true});
  await nav.getByRole('link',{name:'月次レポート',exact:true}).click();
  await page.locator('input[name="month"]').fill('2026-09');
  await page.locator('input[name="month"]').blur();
  for (const [key,value] of Object.entries({views:100,subsDelta:5,retention:50,conversions:2})) await page.locator(`input[name="${key}"]`).fill(String(value));
  await page.getByRole('button',{name:'月次数値を保存してレポート作成',exact:true}).click();
  await page.getByRole('heading',{name:'月次レポート骨子 (2026-09)',exact:true}).waitFor();
  await page.locator('input[name="month"]').fill('2026-10');
  await page.locator('input[name="month"]').blur();
  for (const [key,value] of Object.entries({views:200,subsDelta:8,retention:60,conversions:2})) await page.locator(`input[name="${key}"]`).fill(String(value));
  await page.getByRole('button',{name:'月次数値を保存してレポート作成',exact:true}).click();
  await page.getByRole('heading',{name:'月次レポート骨子 (2026-10)',exact:true}).waitFor();
  assert.match(await page.locator('main').textContent(),/100%/);
  await page.getByRole('button',{name:'Markdownをコピー',exact:true}).click();
  await page.screenshot({path:'WORK/screenshots/report-desktop.png',fullPage:true});
  await page.reload();
  await page.getByRole('heading',{name:'月次レポート',exact:true}).waitFor();
  await nav.getByRole('link',{name:'ホーム',exact:true}).click();
  await page.getByRole('heading',{name:'A社',exact:true}).waitFor();
  await page.goBack(); await page.getByRole('heading',{name:'月次レポート',exact:true}).waitFor();
  await page.goForward(); await page.getByRole('heading',{name:'A社',exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'mobile horizontal overflow');
  await page.screenshot({path:'WORK/screenshots/home-mobile.png',fullPage:true});
  assert.equal(await page.getByRole('navigation').getByRole('link').count(),7);
  assert.equal(errors.length,0,errors.join('\n'));
  console.log('Browser workflow passed: 7 screens, manual recovery, persistence, notes, schedule, brief, report, copy, reload/history and mobile layout.');
  await context.close();
} finally { await browser?.close(); await server.close(); await runtime.dispose(); }
