import type { Goal, IdeaType, Industry, IndustryCaution, MeasureRule, OutlineTemplate, Recommendation, StepDefinition, ThumbnailTemplate, TitleTemplate } from '../types.ts';

const industries: Industry[] = [
  { id: 'career', label: '転職エージェント', shortLabel: '転職', defaultTarget: '自分に合う仕事と転職先を探している方', shortTarget: '転職検討者' },
  { id: 'clinic', label: 'クリニック', shortLabel: '診療', defaultTarget: '受診や治療の選択肢を検討している方', shortTarget: '受診検討者' },
  { id: 'housing', label: '工務店・不動産', shortLabel: '住まい', defaultTarget: '住まいづくりや物件選びを検討している方', shortTarget: '住まい検討者' },
  { id: 'professional', label: '士業', shortLabel: '専門相談', defaultTarget: '専門家への相談を検討している事業者や個人', shortTarget: '相談検討者' },
  { id: 'btob', label: 'BtoB', shortLabel: '法人取引', defaultTarget: '業務上の課題を解決したい企業の担当者', shortTarget: '企業担当者' },
  { id: 'recruitment', label: '採用', shortLabel: '採用', defaultTarget: '働く環境と仕事内容を知りたい求職者', shortTarget: '求職者' },
];
const goals: Goal[] = [
  { id: 'leads', label: '集客', aim: '{target}の疑問を解消し、{industry}の相談・問い合わせにつなげる。', cta: '概要欄の相談窓口と関連情報を確認してもらう。' },
  { id: 'hiring', label: '採用', aim: '{target}に{industry}の仕事と働く環境を伝え、応募の判断材料を届ける。', cta: '概要欄の募集要項を確認し、応募先を案内する。' },
  { id: 'sales', label: '売上', aim: '{target}に{industry}の提供価値と検討条件を伝え、具体的な商談・申込みにつなげる。', cta: '概要欄のサービス内容・条件と申込み窓口を確認してもらう。' },
];
const ideaTypes: IdeaType[] = [
  { id: 'howto', label: 'ノウハウ解説' }, { id: 'faq', label: 'よくある質問' },
  { id: 'case', label: 'ビフォーアフター・事例' }, { id: 'day', label: '1日密着' },
  { id: 'interview', label: '代表・院長対談' }, { id: 'ranking', label: 'ランキング・比較' },
  { id: 'consultation', label: 'お悩み相談' }, { id: 'employee', label: '社員インタビュー' },
];
const recommendations: Recommendation[] = [
  { industry: 'career', goal: 'leads', recommended: ['howto', 'faq', 'consultation'], nonRecommended: [{ ideaType: 'day', reason: '支援者の日常だけでは、転職を検討する視聴者の疑問に答えにくいため。' }] },
  { industry: 'career', goal: 'hiring', recommended: ['employee', 'day', 'interview'], nonRecommended: [{ ideaType: 'ranking', reason: '勤務先の比較順位だけでは、実際の仕事内容や働く環境が伝わりにくいため。' }] },
  { industry: 'career', goal: 'sales', recommended: ['case', 'faq', 'interview'], nonRecommended: [{ ideaType: 'day', reason: '日常の紹介だけでは、支援サービスの検討条件と価値が伝わりにくいため。' }] },
  { industry: 'clinic', goal: 'leads', recommended: ['faq', 'howto', 'consultation'], nonRecommended: [{ ideaType: 'ranking', reason: '医療機関や治療の優劣を断定する比較表現につながりやすいため。' }] },
  { industry: 'clinic', goal: 'hiring', recommended: ['day', 'employee', 'interview'], nonRecommended: [{ ideaType: 'case', reason: '症例の紹介だけでは職務・勤務条件が伝わりにくく、個人情報にも配慮が必要なため。' }] },
  { industry: 'clinic', goal: 'sales', recommended: ['faq', 'howto', 'interview'], nonRecommended: [{ ideaType: 'case', reason: '治療効果の保証や誤認を招く症例表現になるおそれがあるため。' }] },
  { industry: 'housing', goal: 'leads', recommended: ['case', 'howto', 'faq'], nonRecommended: [{ ideaType: 'employee', reason: '社員紹介だけでは、住まいの検討に必要な情報を届けにくいため。' }] },
  { industry: 'housing', goal: 'hiring', recommended: ['day', 'employee', 'interview'], nonRecommended: [{ ideaType: 'ranking', reason: '物件や設備の順位だけでは仕事の魅力や職務内容が伝わりにくいため。' }] },
  { industry: 'housing', goal: 'sales', recommended: ['case', 'ranking', 'faq'], nonRecommended: [{ ideaType: 'day', reason: '現場の日常だけでは価格条件や検討材料が不足しやすいため。' }] },
  { industry: 'professional', goal: 'leads', recommended: ['howto', 'faq', 'consultation'], nonRecommended: [{ ideaType: 'ranking', reason: '専門家や報酬の単純な順位付けは、条件の違いを伝えにくいため。' }] },
  { industry: 'professional', goal: 'hiring', recommended: ['employee', 'day', 'interview'], nonRecommended: [{ ideaType: 'case', reason: '相談事例だけでは勤務環境が見えにくく、守秘義務にも注意が必要なため。' }] },
  { industry: 'professional', goal: 'sales', recommended: ['faq', 'case', 'interview'], nonRecommended: [{ ideaType: 'ranking', reason: '報酬や成功率の比較だけでは、受任条件や専門性の適切な理解につながりにくいため。' }] },
  { industry: 'btob', goal: 'leads', recommended: ['howto', 'case', 'consultation'], nonRecommended: [{ ideaType: 'employee', reason: '社員紹介だけでは企業担当者の業務課題に答えにくいため。' }] },
  { industry: 'btob', goal: 'hiring', recommended: ['employee', 'day', 'interview'], nonRecommended: [{ ideaType: 'ranking', reason: '製品比較だけでは仕事内容や働く環境が伝わりにくいため。' }] },
  { industry: 'btob', goal: 'sales', recommended: ['case', 'ranking', 'faq'], nonRecommended: [{ ideaType: 'day', reason: '日常紹介だけでは導入条件や期待できる価値の説明が不足しやすいため。' }] },
  { industry: 'recruitment', goal: 'leads', recommended: ['howto', 'faq', 'interview'], nonRecommended: [{ ideaType: 'ranking', reason: '企業の順位だけでは仕事選びの根拠と条件を十分に伝えにくいため。' }] },
  { industry: 'recruitment', goal: 'hiring', recommended: ['employee', 'day', 'interview'], nonRecommended: [{ ideaType: 'ranking', reason: '職場の単純な順位付けは、職務や勤務条件の正確な理解につながりにくいため。' }] },
  { industry: 'recruitment', goal: 'sales', recommended: ['case', 'faq', 'consultation'], nonRecommended: [{ ideaType: 'day', reason: '日常紹介だけでは採用支援の提供価値と契約条件を説明しにくいため。' }] },
];
const outlines: OutlineTemplate[] = [
  { ideaType: 'howto', blocks: [
    { kind: 'hook', label: 'フック', ratio: .07, cut: '結論を伝える正面カット', prop: '結論の見出し', position: 'カメラ正面' },
    { kind: 'problem', label: '問題提起', ratio: .13, cut: 'よくある失敗を示す手元カット', prop: '課題の図解', position: '図解の横' },
    { kind: 'main', label: '本論', ratio: .45, cut: '手順ごとの説明と寄りカット', prop: '手順資料', position: '資料を隠さない位置' },
    { kind: 'example', label: '事例', ratio: .20, cut: '手順を実演するカット', prop: '実演に必要な道具', position: '手元が映る位置' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '要点を再確認する正面カット', prop: '要点一覧', position: 'カメラ正面' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '案内先を示す正面カット', prop: '案内先の表示資料', position: 'テロップの余白を空ける位置' },
  ] },
  { ideaType: 'faq', blocks: [
    { kind: 'hook', label: 'フック', ratio: .08, cut: '代表的な質問を読むカット', prop: '質問カード', position: 'カメラ正面' },
    { kind: 'problem', label: '問題提起', ratio: .12, cut: '質問の背景を説明するカット', prop: '質問一覧', position: '画面中央' },
    { kind: 'main', label: '本論', ratio: .50, cut: '質問と回答を交互に収録', prop: '回答の根拠資料', position: '質問表示の横' },
    { kind: 'example', label: '事例', ratio: .15, cut: '条件の異なる例を紹介', prop: '条件比較の図', position: '図の横' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '回答の要点を確認', prop: '回答一覧', position: 'カメラ正面' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '追加質問の窓口を紹介', prop: '相談先の案内', position: 'テロップの余白を空ける位置' },
  ] },
  { ideaType: 'case', blocks: [
    { kind: 'hook', label: 'フック', ratio: .08, cut: '変化の要点を紹介', prop: '使用許諾のある資料', position: 'カメラ正面' },
    { kind: 'problem', label: '問題提起', ratio: .17, cut: '導入前の課題を説明', prop: '匿名化した課題資料', position: '資料の横' },
    { kind: 'main', label: '本論', ratio: .35, cut: '取り組みの過程を説明', prop: '過程の図解', position: '画面中央' },
    { kind: 'example', label: '事例', ratio: .25, cut: '同じ条件で変化を比較', prop: '条件・期間を明記した比較資料', position: '比較資料を隠さない位置' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '適用条件と限界を確認', prop: '条件一覧', position: 'カメラ正面' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '個別相談先を紹介', prop: '相談先の案内', position: 'テロップの余白を空ける位置' },
  ] },
  { ideaType: 'day', blocks: [
    { kind: 'hook', label: 'フック', ratio: .07, cut: '一日の見どころを収録', prop: '当日の予定表', position: '現場入口' },
    { kind: 'problem', label: '問題提起', ratio: .08, cut: '担当業務と目的を説明', prop: '業務の概要資料', position: '安全な待機位置' },
    { kind: 'main', label: '本論', ratio: .55, cut: '業務の流れを時間順に収録', prop: '撮影許諾済みの業務道具', position: '動線を妨げない位置' },
    { kind: 'example', label: '事例', ratio: .15, cut: '工夫している場面を収録', prop: '工夫を示す道具', position: '安全を確保した側面' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '一日の振り返りを収録', prop: '振り返りメモ', position: '静かな場所' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '関連情報と募集案内を収録', prop: '案内資料', position: 'カメラ正面' },
  ] },
  { ideaType: 'interview', blocks: [
    { kind: 'hook', label: 'フック', ratio: .08, cut: '対談の主要テーマを収録', prop: 'テーマカード', position: '対談者が互いに見える位置' },
    { kind: 'problem', label: '問題提起', ratio: .12, cut: '背景と問題意識を聞く', prop: '質問台本', position: '対談の引き画' },
    { kind: 'main', label: '本論', ratio: .45, cut: '回答者の寄りと二人の引きを収録', prop: '根拠資料', position: '視線が自然につながる位置' },
    { kind: 'example', label: '事例', ratio: .20, cut: '具体的な取り組みを聞く', prop: '許諾済みの補足写真', position: '回答者の寄り画' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '対談の要点を確認', prop: '要点メモ', position: '二人の引き画' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '視聴者への案内を収録', prop: '案内資料', position: 'カメラ正面' },
  ] },
  { ideaType: 'ranking', blocks: [
    { kind: 'hook', label: 'フック', ratio: .08, cut: '比較するテーマを提示', prop: '比較対象一覧', position: 'カメラ正面' },
    { kind: 'problem', label: '問題提起', ratio: .12, cut: '比較基準と条件を説明', prop: '評価基準の表', position: '表の横' },
    { kind: 'main', label: '本論', ratio: .50, cut: '各対象を同条件で紹介', prop: '出典付き比較表', position: '比較対象を隠さない位置' },
    { kind: 'example', label: '事例', ratio: .15, cut: '条件別の選び方を紹介', prop: '条件別の事例資料', position: '資料の横' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '対象ごとの向き不向きを確認', prop: '選び方のまとめ', position: 'カメラ正面' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '詳細情報への案内を収録', prop: '出典と案内先', position: 'テロップの余白を空ける位置' },
  ] },
  { ideaType: 'consultation', blocks: [
    { kind: 'hook', label: 'フック', ratio: .08, cut: '相談テーマを紹介', prop: '匿名化した相談文', position: 'カメラ正面' },
    { kind: 'problem', label: '問題提起', ratio: .20, cut: '相談の背景と条件を整理', prop: '前提条件のメモ', position: '相談表示の横' },
    { kind: 'main', label: '本論', ratio: .40, cut: '選択肢と判断の観点を説明', prop: '選択肢の図解', position: '図解の横' },
    { kind: 'example', label: '事例', ratio: .17, cut: '条件別の対応例を紹介', prop: '仮想事例の資料', position: '画面中央' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '判断のポイントを再確認', prop: '要点メモ', position: 'カメラ正面' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '必要に応じた個別相談を案内', prop: '相談先の案内', position: 'テロップの余白を空ける位置' },
  ] },
  { ideaType: 'employee', blocks: [
    { kind: 'hook', label: 'フック', ratio: .08, cut: '仕事の魅力をひと言で紹介', prop: '役割を示す匿名の肩書き', position: 'カメラ正面' },
    { kind: 'problem', label: '問題提起', ratio: .12, cut: '仕事を選んだ背景を聞く', prop: '質問台本', position: 'インタビュー席' },
    { kind: 'main', label: '本論', ratio: .45, cut: '仕事内容と一日の流れを聞く', prop: '業務紹介資料', position: '自然な視線の位置' },
    { kind: 'example', label: '事例', ratio: .20, cut: '成長や連携の具体例を聞く', prop: '撮影許諾済みの現場資料', position: '業務を妨げない位置' },
    { kind: 'summary', label: 'まとめ', ratio: .10, cut: '向いている人と働く条件を確認', prop: '募集条件の資料', position: 'カメラ正面' },
    { kind: 'cta', label: 'CTA', ratio: .05, cut: '募集要項と応募先を紹介', prop: '募集案内', position: 'テロップの余白を空ける位置' },
  ] },
];
const titles: TitleTemplate[] = [
  { id: 'howto-number', ideaType: 'howto', kind: 'number', text: '{industry}で押さえる3つの基本' },
  { id: 'howto-question', ideaType: 'howto', kind: 'question', text: '{target}が知りたい{industry}の始め方は？' },
  { id: 'howto-assertion', ideaType: 'howto', kind: 'assertion', text: '{industry}は基礎を知ることから始まる' },
  { id: 'faq-number', ideaType: 'faq', kind: 'number', text: '{industry}のよくある質問5選' },
  { id: 'faq-question', ideaType: 'faq', kind: 'question', text: '{industry}で気になる疑問、どう考える？' },
  { id: 'faq-assertion', ideaType: 'faq', kind: 'assertion', text: '{target}の疑問をひとつずつ整理' },
  { id: 'case-number', ideaType: 'case', kind: 'number', text: '{industry}の事例から学ぶ3つの視点' },
  { id: 'case-question', ideaType: 'case', kind: 'question', text: '{industry}の取り組みで何が変わった？' },
  { id: 'case-assertion', ideaType: 'case', kind: 'assertion', text: '{industry}の変化を条件とともに読み解く' },
  { id: 'day-number', ideaType: 'day', kind: 'number', text: '{industry}の1日に密着、3つの見どころ' },
  { id: 'day-question', ideaType: 'day', kind: 'question', text: '{industry}の現場はどう動いている？' },
  { id: 'day-assertion', ideaType: 'day', kind: 'assertion', text: '{industry}の仕事を一日の流れで紹介' },
  { id: 'interview-number', ideaType: 'interview', kind: 'number', text: '{industry}の代表に聞く3つの問い' },
  { id: 'interview-question', ideaType: 'interview', kind: 'question', text: '{industry}で大切にしていることは？' },
  { id: 'interview-assertion', ideaType: 'interview', kind: 'assertion', text: '{industry}への思いを対談でひもとく' },
  { id: 'ranking-number', ideaType: 'ranking', kind: 'number', text: '{industry}を比べる3つの判断軸' },
  { id: 'ranking-question', ideaType: 'ranking', kind: 'question', text: '{target}は{industry}をどう選ぶ？' },
  { id: 'ranking-assertion', ideaType: 'ranking', kind: 'assertion', text: '{industry}の選び方は条件で変わる' },
  { id: 'consultation-number', ideaType: 'consultation', kind: 'number', text: '{industry}の悩みを整理する3つの視点' },
  { id: 'consultation-question', ideaType: 'consultation', kind: 'question', text: '{target}の{industry}の悩み、どう考える？' },
  { id: 'consultation-assertion', ideaType: 'consultation', kind: 'assertion', text: '{industry}の悩みを選択肢から考える' },
  { id: 'employee-number', ideaType: 'employee', kind: 'number', text: '{industry}の社員に聞く3つの仕事の話' },
  { id: 'employee-question', ideaType: 'employee', kind: 'question', text: '{industry}ではどんな人が働いている？' },
  { id: 'employee-assertion', ideaType: 'employee', kind: 'assertion', text: '{industry}の働く姿を社員の言葉で紹介' },
];
const thumbnails: ThumbnailTemplate[] = [
  { id: 'howto-1', ideaType: 'howto', text: '{industry}の基本3選' }, { id: 'howto-2', ideaType: 'howto', text: 'まず知りたい手順' },
  { id: 'faq-1', ideaType: 'faq', text: '{industry}の疑問に回答' }, { id: 'faq-2', ideaType: 'faq', text: '気になる5つの質問' },
  { id: 'case-1', ideaType: 'case', text: '{industry}の変化と条件' }, { id: 'case-2', ideaType: 'case', text: '事例でわかる取り組み' },
  { id: 'day-1', ideaType: 'day', text: '{industry}の1日に密着' }, { id: 'day-2', ideaType: 'day', text: '現場の仕事を紹介' },
  { id: 'interview-1', ideaType: 'interview', text: '{industry}への思い' }, { id: 'interview-2', ideaType: 'interview', text: '代表が語る仕事の軸' },
  { id: 'ranking-1', ideaType: 'ranking', text: '{industry}を条件で比較' }, { id: 'ranking-2', ideaType: 'ranking', text: '選び方の3つの軸' },
  { id: 'consultation-1', ideaType: 'consultation', text: '{industry}のお悩み相談' }, { id: 'consultation-2', ideaType: 'consultation', text: '選択肢を一緒に整理' },
  { id: 'employee-1', ideaType: 'employee', text: '{industry}で働く人の声' }, { id: 'employee-2', ideaType: 'employee', text: '仕事と成長を聞く' },
];
const cautions: IndustryCaution[] = [
  { industry: 'career', items: ['転職・内定・年収の向上を保証する表現を避ける。', '求人条件・実績の出典と対象期間を確認し、個人情報を掲載しない。'] },
  { industry: 'clinic', items: ['治療効果の断定・保証、他院より優れていると誤認させる表現を避ける。', '症例紹介は条件・リスク等の必要な情報と掲載可否を確認し、医療広告に関する確認を行う。'] },
  { industry: 'housing', items: ['資産価値・値上がり・耐久性を保証する表現や、根拠のない最上級表現を避ける。', '価格・面積・立地・施工事例の条件と時点を明示し、所有者等の掲載許諾を確認する。'] },
  { industry: 'professional', items: ['成功・勝訴・節税を保証する表現や、条件の異なる報酬の単純比較を避ける。', '守秘義務と所属団体等の広告ルールを確認し、個別事例は匿名化と掲載可否を確認する。'] },
  { industry: 'btob', items: ['売上・生産性などの成果を一律に保証する表現を避ける。', '比較条件・出典・実績の範囲を明示し、取引先の機密と掲載許諾を確認する。'] },
  { industry: 'recruitment', items: ['給与・待遇・働き方の確約や実態と異なる募集表現を避ける。', '募集条件の最新情報を確認し、差別的な表現や応募者・社員の個人情報を掲載しない。'] },
];
/** Each duration is the business-day interval from the preceding milestone. */
const steps: StepDefinition[] = [
  { id: 'plan', label: '企画確定', businessDays: 1 }, { id: 'script', label: '台本確定', businessDays: 2 },
  { id: 'shoot', label: '撮影', businessDays: 1 }, { id: 'draft', label: '編集初稿', businessDays: 3 },
  { id: 'revision', label: '修正', businessDays: 2 }, { id: 'publish', label: '投稿', businessDays: 1 },
];
const measureRules: MeasureRule[] = [
  { id: 'cta-path', conditions: [{ metric: 'views', trend: 'up' }, { metric: 'conversions', trend: 'flat' }], title: '概要欄・CTAの導線見直し', action: '視聴後の相談・応募先をひとつに絞り、概要欄と動画内CTAの案内をそろえる。' },
  { id: 'conversion-gap', conditions: [{ metric: 'views', trend: 'up' }, { metric: 'conversions', trend: 'down' }], title: '視聴者と案内内容の整合を確認', action: '動画で約束した情報と案内先の内容・条件を照合し、離脱しやすい箇所を確認する。' },
  { id: 'hook-drop', conditions: [{ metric: 'views', trend: 'up' }, { metric: 'retention', trend: 'down' }], title: '冒頭とタイトルの期待をそろえる', action: '冒頭で結論と対象者を示し、タイトル・サムネイルで伝えた内容に早く入る。' },
  { id: 'reach-down', conditions: [{ metric: 'views', trend: 'down' }, { metric: 'retention', trend: 'up' }], title: '届き方を見直す', action: '内容を維持しながらタイトル・サムネイルの対象者と具体性を見直し、関連動画からの導線を確認する。' },
  { id: 'content-down', conditions: [{ metric: 'views', trend: 'down' }, { metric: 'retention', trend: 'down' }], title: 'テーマと構成を絞り直す', action: '視聴者の疑問をひとつに絞り、前置きを短くして本論を早める。' },
  { id: 'subscribe-gap', conditions: [{ metric: 'views', trend: 'up' }, { metric: 'subsDelta', trend: 'flat' }], title: '継続視聴する理由を伝える', action: '次回のテーマとチャンネルで扱う内容を示し、シリーズ内の回遊を促す。' },
  { id: 'subscriber-down', conditions: [{ metric: 'subsDelta', trend: 'down' }], title: '継続視聴のテーマを確認', action: '視聴者が期待するテーマの一貫性と更新間隔を確認し、関連する次回企画を用意する。' },
  { id: 'retention-down', conditions: [{ metric: 'retention', trend: 'down' }], title: '離脱しやすい説明を短くする', action: '導入・重複説明・長い間を見直し、具体例や図解を本論に加える。' },
  { id: 'conversion-down', conditions: [{ metric: 'conversions', trend: 'down' }], title: '問い合わせ・応募の手順を確認', action: '案内先の表示と入力の手間を確認し、相談・応募の条件をわかりやすく伝える。' },
  { id: 'steady', conditions: [{ metric: 'views', trend: 'flat' }, { metric: 'conversions', trend: 'flat' }], title: 'ひとつの変更で次月比較', action: '企画型・タイトル・CTAのうちひとつだけ変更し、翌月に同じ指標で比較する。' },
  { id: 'grow', conditions: [{ metric: 'views', trend: 'up' }, { metric: 'conversions', trend: 'up' }], title: '成果の出たテーマを展開', action: '反応のあったテーマを関連する質問や事例へ展開し、同じ案内先につなげる。' },
  { id: 'efficient', conditions: [{ metric: 'views', trend: 'down' }, { metric: 'conversions', trend: 'up' }], title: '成果につながる視聴者を深掘り', action: '相談・応募につながったテーマの共通点を確認し、その対象者向けの企画を増やす。' },
];
export const CATALOG = { industries, goals, ideaTypes, recommendations, outlines, titles, thumbnails, cautions, steps, measureRules };
